"""Build a noindexed review copy of the site for GitHub Pages at /junkremovalbigbear-preview/.
Never adds a CNAME. Usage: python3 _build/make_preview.py <outdir>"""
import os, re, shutil, sys
SRC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = sys.argv[1]
BASE = '/junkremovalbigbear-preview/'
SKIP = {'.git', '_build', 'README.md', 'LAUNCH-GUIDE.md', '_config.yml', 'CNAME', 'sitemap.xml', '.gitignore', 'robots.txt'}
if os.path.exists(OUT):
    for n in os.listdir(OUT):
        if n == '.git': continue
        p = os.path.join(OUT, n); shutil.rmtree(p) if os.path.isdir(p) else os.remove(p)
os.makedirs(OUT, exist_ok=True)
for n in os.listdir(SRC):
    if n in SKIP: continue
    s, d = os.path.join(SRC, n), os.path.join(OUT, n)
    shutil.copytree(s, d) if os.path.isdir(s) else shutil.copy2(s, d)
BANNER = ('<div style="background:#b3261e;color:#fff;text-align:center;padding:8px 12px;font:600 14px/1.4 system-ui,sans-serif">'
          'PREVIEW — not the live site. Some details are still pending confirmation. Illustrations are AI-generated general scenes. '
          'Dashed boxes mark spots for real photos.</div>')
def fix(h):
    h = re.sub(r'(href|src)="/(?!/)', lambda m: f'{m.group(1)}="{BASE}', h)
    h = re.sub(r'srcset="([^"]+)"', lambda m: 'srcset="' + re.sub(r'(^|,\s*)/(?!/)', lambda k: k.group(1) + BASE, m.group(1)) + '"', h)
    h = h.replace('url(/', 'url(' + BASE)
    h = re.sub(r'<meta name="robots"[^>]*>', '', h)
    h = h.replace('<head>', '<head>\n<meta name="robots" content="noindex, nofollow">', 1)
    h = re.sub(r'(<body[^>]*>)', r'\1' + BANNER, h, count=1)
    h = re.sub(r'<!-- PHOTO-SLOT: (.*?) -->', r'<div class="photo-slot">📷 Photo slot: \1</div>', h)
    return h
for root, _, files in os.walk(OUT):
    if '/.git' in root: continue
    for f in files:
        p = os.path.join(root, f)
        if f.endswith(('.html', '.css')):
            t = open(p, encoding='utf-8').read(); open(p, 'w', encoding='utf-8').write(fix(t))
open(os.path.join(OUT, 'robots.txt'), 'w').write('User-agent: *\nDisallow: /\n')
open(os.path.join(OUT, '.nojekyll'), 'w').write('')
open(os.path.join(OUT, 'README.md'), 'w').write('# Junk Removal Big Bear — redesign preview\n\nNoindexed review copy of branch `redesign-2026` of nicholasckc/junkremovalbigbear. Not the live site. Generated by `_build/make_preview.py`; do not edit here.\n')
assert not os.path.exists(os.path.join(OUT, 'CNAME'))
print('preview written to', OUT)
